apiVersion: v1
kind: ConfigMap
metadata:
  name: alitellm-auth-factory-config
  labels:
    app: alitellm-auth
data:
  factory-config.json: |
    {
      "team": {
        "max_budget": 500,
        "budget_duration": "30d",
        "tpm_limit": 5000000,
        "rpm_limit": 500
      },
      "user": {
        "max_parallel_requests": 5,
        "rpm_limit": 10,
        "tpm_limit": 100,
        "max_budget": 10,
        "budget_duration": "24h",
        "metadata": {
          "rpm_limit_type": "best_effort_throughput",
          "tpm_limit_type": "best_effort_throughput"
        }
      }
    }
