apiVersion: v1
kind: ConfigMap
metadata:
  name: alitellm-auth-factory-config
  labels:
    app: alitellm-auth
data:
  factory-config.json: |
    {
      "team": {
        "rpm_limit": 100,
        "tpm_limit": 1000000,
        "max_budget": 200,
        "budget_duration": "30d",
        "metadata": {
          "rpm_limit_type": "best_effort_throughput",
          "tpm_limit_type": "best_effort_throughput"
        }
      },
      "user": {
        "rpm_limit": 100,
        "tpm_limit": 1000000,
        "max_budget": 100,
        "budget_duration": "30d",
        "metadata": {
          "rpm_limit_type": "best_effort_throughput",
          "tpm_limit_type": "best_effort_throughput"
        }
      }
    }
