{{- if .Values.authz.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "alitellm-auth.fullname" . }}-authz
  labels:
    {{- include "alitellm-auth.labels" . | nindent 4 }}
    app.kubernetes.io/component: authz
spec:
  ports:
    - name: grpc
      port: 9001
      targetPort: grpc
      appProtocol: grpc
  selector:
    {{- include "alitellm-auth.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: authz
{{- end }}
