{{- if .Values.authz.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "alitellm-auth.fullname" . }}-authz
  labels:
    {{- include "alitellm-auth.labels" . | nindent 4 }}
    app.kubernetes.io/component: authz
spec:
  minAvailable: {{ .Values.authz.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "alitellm-auth.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: authz
{{- end }}
